{
    title: "Design de Sobrancelhas",
    description: "Modelagem perfeita que realça sua beleza natural",
    price: "R$ 70",
    duration: "40 min",
    image: serviceDesign,
  },
  {
    title: "Design com Henna",
    description: "Design + coloração com henna para sobrancelhas mais marcantes",
    price: "R$ 80",
    duration: "1h",
    image: serviceDesign,
  },
  {
    title: "Depilação na Linha",
    description: "Remoção precisa de pelos faciais",
    price: "A partir de R$ 40",
    duration: "30 min",
    image: serviceDesign,
  },
  {
    title: "Lash Lifting",
    description: "Curvatura e alongamento natural dos cílios",
    price: "R$ 160",
    duration: "1h10min",
    image: serviceLashes,
  },
  {
    title: "Brow Lamination",
    description: "Laminação de sobrancelhas para um efeito disciplinado",
    price: "R$ 160",
    duration: "1h10min",
    image: serviceDesign,
  },
  {
    title: "Micropigmentação Blading Fio a Fio",
    description: "Técnica realista que imita fios naturais",
    price: "R$ 400",
    duration: "2h",
    image: serviceMicro,
  },
  {
    title: "Micropigmentação Shadow",
    description: "Efeito esfumado e sombreado nas sobrancelhas",
    price: "R$ 450",
    duration: "2h",
    image: serviceMicro,
  },
  {
    title: "Limpeza de Pele",
    description: "Tratamento facial completo e revitalizante",
    price: "R$ 120",
    duration: "1h20min",
    image: serviceDesign,
  },
  {
    title: "Extensão de Cílios - Volume Brasileiro",
    description: "Volume natural e elegante",
    price: "R$ 140",
    duration: "2h30min",
    image: serviceLashes,
  },
  {
    title: "Extensão de Cílios - Volume Egípcio",
    description: "Volume dramático e impactante",
    price: "R$ 160",
    duration: "2h30min",
    image: serviceLashes,
  },
  {
    title: "Extensão de Cílios - Volume Médio",
    description: "Equilíbrio entre natural e volumoso",
    price: "R$ 160",
    duration: "2h30min",
    image: serviceLashes,
  },
